### ISSUE TITLE
Scroll to bottom

### ISSUE THREAD

**Issue by ingfdoaguirre** [EkhlasMridha/react-cool-scrollbar#2]
Hi.

Is there any special method to scroll the bar to the botom? Or how to do it.

Thank you

**Comment by EkhlasMridha** [comment]
Hi, Currently we don't have any. But it's a good idea to include, i will implement it. And you are open to contribute too

**Comment by EkhlasMridha** [comment]
Now, you can pass a ref object to the `ReactCoolScrollbar` component and use the ref to scroll your page programmitcally as we do in basic javascript. Follow the onScrollTop function to implement scrollToBottom event on your page.
` 
    function App() { 

        const scrollRef = useRef<HTMLDivElement>(null);

        const onScrollTop = () => {
             scrollRef.current?.scrollTo({
                 behavior: "smooth",
                 top: scrollRef.current.scrollHeight,
            });
        };

        return (
            <div className="app">
                <ReactCoolScrollbar scrollBarVisibility="onscroll" ref={scrollRef}>
               <div>
                   Your contents
              </div>
              </ReactCoolScrollbar>
          </div>
       );
    }`
